<?php
/**
 * AllocateWithCarrierResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\Electio
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Electio API
 *
 * A minimal Electio client
 *
 * OpenAPI spec version: 1.0.9
 * Contact: chris@hemmin.gs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChrisHemmings\Electio;

/**
 * AllocateWithCarrierResponseTest Class Doc Comment
 *
 * @category    Class
 * @description AllocateWithCarrierResponse
 * @package     ChrisHemmings\Electio
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AllocateWithCarrierResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AllocateWithCarrierResponse"
     */
    public function testAllocateWithCarrierResponse()
    {
    }

    /**
     * Test attribute "api_links"
     */
    public function testPropertyApiLinks()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "consignment_legs"
     */
    public function testPropertyConsignmentLegs()
    {
    }

    /**
     * Test attribute "carrier_reference"
     */
    public function testPropertyCarrierReference()
    {
    }

    /**
     * Test attribute "carrier_name"
     */
    public function testPropertyCarrierName()
    {
    }

    /**
     * Test attribute "carrier_service_reference"
     */
    public function testPropertyCarrierServiceReference()
    {
    }

    /**
     * Test attribute "carrier_service_name"
     */
    public function testPropertyCarrierServiceName()
    {
    }
}
