<?php
/**
 * ConsignmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\Electio
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Electio API
 *
 * A cut down Electio API Swagger Definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: chris@hemmin.gs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChrisHemmings\Electio;

/**
 * ConsignmentTest Class Doc Comment
 *
 * @category    Class */
// * @description Consignment
/**
 * @package     ChrisHemmings\Electio
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Consignment"
     */
    public function testConsignment()
    {

    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {

    }

    /**
     * Test attribute "customer_reference"
     */
    public function testPropertyCustomerReference()
    {

    }

    /**
     * Test attribute "consignment_reference_provided_by_customer"
     */
    public function testPropertyConsignmentReferenceProvidedByCustomer()
    {

    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {

    }

    /**
     * Test attribute "requested_collection_date"
     */
    public function testPropertyRequestedCollectionDate()
    {

    }

    /**
     * Test attribute "collection_date"
     */
    public function testPropertyCollectionDate()
    {

    }

    /**
     * Test attribute "expected_delivery_date"
     */
    public function testPropertyExpectedDeliveryDate()
    {

    }

    /**
     * Test attribute "scheduled_delivery_date"
     */
    public function testPropertyScheduledDeliveryDate()
    {

    }

    /**
     * Test attribute "collected_date"
     */
    public function testPropertyCollectedDate()
    {

    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {

    }

    /**
     * Test attribute "attempted_delivery_date"
     */
    public function testPropertyAttemptedDeliveryDate()
    {

    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {

    }

    /**
     * Test attribute "packages"
     */
    public function testPropertyPackages()
    {

    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {

    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {

    }

    /**
     * Test attribute "allocation"
     */
    public function testPropertyAllocation()
    {

    }

    /**
     * Test attribute "failed_allocation"
     */
    public function testPropertyFailedAllocation()
    {

    }

    /**
     * Test attribute "customs_documentation"
     */
    public function testPropertyCustomsDocumentation()
    {

    }

    /**
     * Test attribute "consignment_state"
     */
    public function testPropertyConsignmentState()
    {

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {

    }

    /**
     * Test attribute "have_labels_ever_been_printed"
     */
    public function testPropertyHaveLabelsEverBeenPrinted()
    {

    }

    /**
     * Test attribute "date_labels_were_first_printed"
     */
    public function testPropertyDateLabelsWereFirstPrinted()
    {

    }

    /**
     * Test attribute "is_late"
     */
    public function testPropertyIsLate()
    {

    }

    /**
     * Test attribute "late_for_customer"
     */
    public function testPropertyLateForCustomer()
    {

    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {

    }

    /**
     * Test attribute "location_information"
     */
    public function testPropertyLocationInformation()
    {

    }

    /**
     * Test attribute "consignment_legs"
     */
    public function testPropertyConsignmentLegs()
    {

    }

}
