<?php
/**
 * CustomsDocumentationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\Electio
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Electio API
 *
 * A cut down Electio API Swagger Definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: chris@hemmin.gs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChrisHemmings\Electio;

/**
 * CustomsDocumentationTest Class Doc Comment
 *
 * @category    Class */
// * @description CustomsDocumentation
/**
 * @package     ChrisHemmings\Electio
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomsDocumentationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CustomsDocumentation"
     */
    public function testCustomsDocumentation()
    {

    }

    /**
     * Test attribute "importers_vat_number"
     */
    public function testPropertyImportersVatNumber()
    {

    }

    /**
     * Test attribute "category_type"
     */
    public function testPropertyCategoryType()
    {

    }

    /**
     * Test attribute "shipper_customs_reference"
     */
    public function testPropertyShipperCustomsReference()
    {

    }

    /**
     * Test attribute "importers_tax_code"
     */
    public function testPropertyImportersTaxCode()
    {

    }

    /**
     * Test attribute "importers_telephone"
     */
    public function testPropertyImportersTelephone()
    {

    }

    /**
     * Test attribute "importers_fax"
     */
    public function testPropertyImportersFax()
    {

    }

    /**
     * Test attribute "cn23_comments"
     */
    public function testPropertyCn23Comments()
    {

    }

    /**
     * Test attribute "references_of_attached_invoices"
     */
    public function testPropertyReferencesOfAttachedInvoices()
    {

    }

    /**
     * Test attribute "references_of_attached_licences"
     */
    public function testPropertyReferencesOfAttachedLicences()
    {

    }

    /**
     * Test attribute "category_type_explanation"
     */
    public function testPropertyCategoryTypeExplanation()
    {

    }

    /**
     * Test attribute "declaration_date"
     */
    public function testPropertyDeclarationDate()
    {

    }

    /**
     * Test attribute "office_of_posting"
     */
    public function testPropertyOfficeOfPosting()
    {

    }

    /**
     * Test attribute "reason_for_export"
     */
    public function testPropertyReasonForExport()
    {

    }

    /**
     * Test attribute "shipping_terms"
     */
    public function testPropertyShippingTerms()
    {

    }

    /**
     * Test attribute "shippers_vat_number"
     */
    public function testPropertyShippersVatNumber()
    {

    }

    /**
     * Test attribute "designated_person_responsible"
     */
    public function testPropertyDesignatedPersonResponsible()
    {

    }

}
