<?php
/**
 * FailedAllocationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\Electio
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Electio API
 *
 * A cut down Electio API Swagger Definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: chris@hemmin.gs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChrisHemmings\Electio;

/**
 * FailedAllocationTest Class Doc Comment
 *
 * @category    Class */
// * @description FailedAllocation
/**
 * @package     ChrisHemmings\Electio
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FailedAllocationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "FailedAllocation"
     */
    public function testFailedAllocation()
    {

    }

    /**
     * Test attribute "carrier_service_group_reference"
     */
    public function testPropertyCarrierServiceGroupReference()
    {

    }

    /**
     * Test attribute "mpd_carrier_service_group_name"
     */
    public function testPropertyMpdCarrierServiceGroupName()
    {

    }

    /**
     * Test attribute "mpd_carrier_service_reference"
     */
    public function testPropertyMpdCarrierServiceReference()
    {

    }

    /**
     * Test attribute "mpd_carrier_service_name"
     */
    public function testPropertyMpdCarrierServiceName()
    {

    }

    /**
     * Test attribute "attempted_allocation_date"
     */
    public function testPropertyAttemptedAllocationDate()
    {

    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {

    }

}
