<?php
/**
 * QuotesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\Electio
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Electio API
 *
 * A minimal Electio client
 *
 * OpenAPI spec version: 1.0.5
 * Contact: chris@hemmin.gs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChrisHemmings\Electio;

/**
 * QuotesTest Class Doc Comment
 *
 * @category    Class
 * @description Quotes
 * @package     ChrisHemmings\Electio
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuotesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Quotes"
     */
    public function testQuotes()
    {
    }

    /**
     * Test attribute "quote_reference"
     */
    public function testPropertyQuoteReference()
    {
    }

    /**
     * Test attribute "requestor"
     */
    public function testPropertyRequestor()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "consignment_reference"
     */
    public function testPropertyConsignmentReference()
    {
    }

    /**
     * Test attribute "consignment_reference_provided_by_customer"
     */
    public function testPropertyConsignmentReferenceProvidedByCustomer()
    {
    }

    /**
     * Test attribute "mpd_carrier_service_reference"
     */
    public function testPropertyMpdCarrierServiceReference()
    {
    }

    /**
     * Test attribute "mpd_carrier_service_source"
     */
    public function testPropertyMpdCarrierServiceSource()
    {
    }

    /**
     * Test attribute "mpd_carrier_service"
     */
    public function testPropertyMpdCarrierService()
    {
    }

    /**
     * Test attribute "carrier_reference"
     */
    public function testPropertyCarrierReference()
    {
    }

    /**
     * Test attribute "origin_address"
     */
    public function testPropertyOriginAddress()
    {
    }

    /**
     * Test attribute "destination_address"
     */
    public function testPropertyDestinationAddress()
    {
    }

    /**
     * Test attribute "collection_date"
     */
    public function testPropertyCollectionDate()
    {
    }

    /**
     * Test attribute "earliest_delivery_date"
     */
    public function testPropertyEarliestDeliveryDate()
    {
    }

    /**
     * Test attribute "latest_delivery_date"
     */
    public function testPropertyLatestDeliveryDate()
    {
    }

    /**
     * Test attribute "base_price"
     */
    public function testPropertyBasePrice()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "carrier_account_owner"
     */
    public function testPropertyCarrierAccountOwner()
    {
    }

    /**
     * Test attribute "is_electio_service"
     */
    public function testPropertyIsElectioService()
    {
    }

    /**
     * Test attribute "service_direction"
     */
    public function testPropertyServiceDirection()
    {
    }
}
