<?php
/**
 * ConsignmentLeg
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\Electio
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Electio API
 *
 * A minimal Electio client
 *
 * OpenAPI spec version: 1.0.1
 * Contact: chris@hemmin.gs
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ChrisHemmings\Electio\Client\Model;

use \ArrayAccess;

/**
 * ConsignmentLeg Class Doc Comment
 *
 * @category    Class
 * @package     ChrisHemmings\Electio
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentLeg implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ConsignmentLeg';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'leg' => 'int',
        'tracking_reference' => 'string',
        'carrier_reference' => 'string',
        'carrier_name' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'leg' => 'Leg',
        'tracking_reference' => 'TrackingReference',
        'carrier_reference' => 'CarrierReference',
        'carrier_name' => 'CarrierName'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'leg' => 'setLeg',
        'tracking_reference' => 'setTrackingReference',
        'carrier_reference' => 'setCarrierReference',
        'carrier_name' => 'setCarrierName'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'leg' => 'getLeg',
        'tracking_reference' => 'getTrackingReference',
        'carrier_reference' => 'getCarrierReference',
        'carrier_name' => 'getCarrierName'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['leg'] = isset($data['leg']) ? $data['leg'] : null;
        $this->container['tracking_reference'] = isset($data['tracking_reference']) ? $data['tracking_reference'] : null;
        $this->container['carrier_reference'] = isset($data['carrier_reference']) ? $data['carrier_reference'] : null;
        $this->container['carrier_name'] = isset($data['carrier_name']) ? $data['carrier_name'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets leg
     * @return int
     */
    public function getLeg()
    {
        return $this->container['leg'];
    }

    /**
     * Sets leg
     * @param int $leg
     * @return $this
     */
    public function setLeg($leg)
    {
        $this->container['leg'] = $leg;

        return $this;
    }

    /**
     * Gets tracking_reference
     * @return string
     */
    public function getTrackingReference()
    {
        return $this->container['tracking_reference'];
    }

    /**
     * Sets tracking_reference
     * @param string $tracking_reference
     * @return $this
     */
    public function setTrackingReference($tracking_reference)
    {
        $this->container['tracking_reference'] = $tracking_reference;

        return $this;
    }

    /**
     * Gets carrier_reference
     * @return string
     */
    public function getCarrierReference()
    {
        return $this->container['carrier_reference'];
    }

    /**
     * Sets carrier_reference
     * @param string $carrier_reference
     * @return $this
     */
    public function setCarrierReference($carrier_reference)
    {
        $this->container['carrier_reference'] = $carrier_reference;

        return $this;
    }

    /**
     * Gets carrier_name
     * @return string
     */
    public function getCarrierName()
    {
        return $this->container['carrier_name'];
    }

    /**
     * Sets carrier_name
     * @param string $carrier_name
     * @return $this
     */
    public function setCarrierName($carrier_name)
    {
        $this->container['carrier_name'] = $carrier_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\ChrisHemmings\Electio\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\ChrisHemmings\Electio\ObjectSerializer::sanitizeForSerialization($this));
    }
}


